# docker-compose -f docker-compose-db.yaml up --build
version: "3.9"
services:
  postgres:
    build: . # Используем Dockerfile в текущей директории
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "thai"  
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Монтируем скрипт для загрузки данных
    ports:
      - "9876:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thai"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G # RAM

volumes:
  pg_data:
